### ISSUE TITLE
take into account alphastrike config for the CSG scripts

### ISSUE THREAD

**Issue by oufy** [JTFF-mission-scripts/jtff-templates#15]

**Comment by alexproust** [comment]
Si on configure l'airboss avec des durées d'event de genre 150min ca permettrait facilement d'avoir un PA en mode alphastrike non? Ca permet de laisser un long crénaux pour tous les décollages. Puis pendant la mission le PA fait demi-tour et lance la phase de recovery 2h30 après la dépause. T'en penses quoi?

**Comment by oufy** [comment]
> Si on configure l'airboss avec des durées d'event de genre 150min ca permettrait facilement d'avoir un PA en mode alphastrike non? Ca permet de laisser un long crénaux pour tous les décollages. Puis pendant la mission le PA fait demi-tour et lance la phase de recovery 2h30 après la dépause. T'en penses quoi?

le codage etait pas bien long comme ca on peut choisir : alpha ou cyclic
