### ISSUE TITLE
CAP IA at north of Turkey not attack

### ISSUE THREAD

**Issue by alexproust** [JTFF-mission-scripts/jtff-templates#7]
The F-16 spawn in the CAP IA training zone at the south of Turkey does not attack.

**Comment by oufy** [comment]
tu as bien vu qu'il y a 2 zones : les IA ne sont censées engager que lorsqu'un bleu entre dans la zone la plus grande.
En attendant que quelqu'un rentre dans cette zone les IA restent en patrouille dans la zone plus petite

**Comment by alexproust** [comment]
J'ai pu faire de la patrouille serré avec eux. Je te redis si j'arrive é reproduire le bug

**Comment by oufy** [comment]
ok, je vais regarder ca alors : j'ai deja eu le pb mais c'etait réglé. y a du avoir une regression qqpart

**Comment by oufy** [comment]
pb fixed : les IA n'avait aucune tache globale assignée, je les ai passé en CAP et c'est repassé offensif :)
